### ISSUE TITLE
1.12.2 Mod Registry issue, doubles the mod's loading with certain launchers.

### ISSUE THREAD

**Issue by Ski-z** [SkpC9/Normal-Damage#1]
With certain mod launchers (GDLauncher for example), the mod is registered twice. This is a rare issue, but one I've only ever seen once before.

![image](https://github.com/SkpC9/Normal-Damage/assets/107653759/6b842765-1b86-4a22-9338-12fe79c33cfd)

When there is only one instance in the /mods folder. I have a friend who fixed his mod with this same issue, I can ask him how he fixed it.

**Comment by SkpC9** [comment]
Thanks for your report, I used Prism Launcher to test this mod, that didn't have this issue.
I searched online and found several pages about it.
[https://github.com/13rac1/Minecraft-Water-Erosion/issues/15](url)
[https://github.com/SpongePowered/Mixin/issues/253](url)
[https://www.minecraftforum.net/forums/support/java-edition-support/1956864-you-have-mod-sources-that-are-duplicate-within](url)
[https://forums.minecraftforge.net/topic/9815-double-mod-bug/](url)
Seems that I have to add a line to build.gradle file. I tried it, and GDlauncher can launch with no problem. I think this issue is fixed now, you can download the latest version.
